"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import jsPDF from "jspdf";
import { supabase } from "../../../../lib/supabase";

interface Invoice {
  id: number;
  client_name: string;
  client_email: string;
  amount: number;
  due_date: string;
  status: string;
  tone: string;
}

export default function InvoiceDetailsPage() {
  const params = useParams();
  const router = useRouter();

  const [loading, setLoading] = useState(true);
  const [invoice, setInvoice] = useState<Invoice | null>(null);

  useEffect(() => {
    fetchInvoice();
  }, []);

  async function fetchInvoice() {
    const { data, error } = await supabase
      .from("invoices")
      .select("*")
      .eq("id", params.id)
      .single();

    if (!error) {
      setInvoice(data);
    }

    setLoading(false);
  }

  async function deleteInvoice() {
    const ok = confirm(
      "Are you sure you want to delete this invoice?"
    );

    if (!ok) return;

    const { error } = await supabase
      .from("invoices")
      .delete()
      .eq("id", params.id);

    if (error) {
      alert(error.message);
      return;
    }

    alert("Invoice deleted successfully.");

    router.push("/dashboard/invoices");
  }

  function sendReminder() {
    alert(
      `Reminder sent successfully to ${invoice?.client_email}`
    );
  }

  function downloadPDF() {
    if (!invoice) return;

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("Invoice", 20, 20);

    doc.line(20, 26, 190, 26);

    doc.setFontSize(13);

    doc.text(`Invoice ID : ${invoice.id}`, 20, 40);
    doc.text(`Client Name : ${invoice.client_name}`, 20, 52);
    doc.text(`Client Email : ${invoice.client_email}`, 20, 64);
    doc.text(`Amount : $${invoice.amount}`, 20, 76);
    doc.text(`Due Date : ${invoice.due_date}`, 20, 88);
    doc.text(`Status : ${invoice.status}`, 20, 100);
    doc.text(`Reminder Tone : ${invoice.tone}`, 20, 112);

    doc.line(20, 122, 190, 122);

    doc.setFontSize(11);

    doc.text(
      "Generated by InvoiceNudge",
      20,
      138
    );

    doc.save(`Invoice-${invoice.id}.pdf`);
  }

  if (loading) {
    return (
      <div className="flex h-96 items-center justify-center">
        <div className="h-12 w-12 animate-spin rounded-full border-4 border-blue-600 border-t-transparent"></div>
      </div>
    );
  }

  if (!invoice) {
    return (
      <div className="rounded-xl bg-white p-10 text-center shadow">
        <h2 className="text-2xl font-bold text-red-600">
          Invoice Not Found
        </h2>

        <Link
          href="/dashboard/invoices"
          className="mt-6 inline-block rounded-lg bg-blue-600 px-6 py-3 text-white"
        >
          Back to Invoices
        </Link>
      </div>
    );
  }

  return (
        <div className="mx-auto max-w-5xl rounded-2xl bg-white p-8 shadow-xl">

      <div className="mb-8 flex items-center justify-between">

        <div>
          <h1 className="text-3xl font-bold text-gray-800">
            Invoice Details
          </h1>

          <p className="mt-2 text-gray-500">
            View complete invoice information.
          </p>
        </div>

        <Link
          href="/dashboard/invoices"
          className="rounded-lg bg-gray-700 px-5 py-3 text-white transition hover:bg-gray-800"
        >
          Back
        </Link>

      </div>

      <div className="grid gap-6 md:grid-cols-2">

        <div className="rounded-xl border bg-gray-50 p-6">
          <h3 className="mb-2 text-sm text-gray-500">
            Client Name
          </h3>

          <p className="text-2xl font-bold">
            {invoice.client_name}
          </p>
        </div>

        <div className="rounded-xl border bg-gray-50 p-6">
          <h3 className="mb-2 text-sm text-gray-500">
            Client Email
          </h3>

          <p className="text-xl font-semibold break-all">
            {invoice.client_email}
          </p>
        </div>

        <div className="rounded-xl border bg-green-50 p-6">
          <h3 className="mb-2 text-sm text-gray-500">
            Invoice Amount
          </h3>

          <p className="text-4xl font-bold text-green-600">
            ${invoice.amount}
          </p>
        </div>

        <div className="rounded-xl border bg-blue-50 p-6">
          <h3 className="mb-2 text-sm text-gray-500">
            Due Date
          </h3>

          <p className="text-2xl font-bold">
            {invoice.due_date}
          </p>
        </div>

        <div className="rounded-xl border p-6">
          <h3 className="mb-3 text-sm text-gray-500">
            Status
          </h3>

          <span
            className={`rounded-full px-4 py-2 text-sm font-semibold text-white ${
              invoice.status === "paid"
                ? "bg-green-500"
                : invoice.status === "pending"
                ? "bg-yellow-500"
                : "bg-red-500"
            }`}
          >
            {invoice.status.toUpperCase()}
          </span>
        </div>

        <div className="rounded-xl border p-6">
          <h3 className="mb-2 text-sm text-gray-500">
            Reminder Tone
          </h3>

          <p className="text-xl font-bold capitalize">
            {invoice.tone}
          </p>
        </div>

      </div>

      <div className="mt-10 grid gap-4 md:grid-cols-4">

        <Link
          href={`/dashboard/invoices/edit/${invoice.id}`}
          className="rounded-lg bg-blue-600 py-3 text-center font-semibold text-white transition hover:bg-blue-700"
        >
          Edit
        </Link>

        <button
          onClick={sendReminder}
          className="rounded-lg bg-yellow-500 py-3 font-semibold text-white transition hover:bg-yellow-600"
        >
          Send Reminder
        </button>

        <button
          onClick={downloadPDF}
          className="rounded-lg bg-green-600 py-3 font-semibold text-white transition hover:bg-green-700"
        >
          Download PDF
        </button>

        <button
          onClick={deleteInvoice}
          className="rounded-lg bg-red-600 py-3 font-semibold text-white transition hover:bg-red-700"
        >
          Delete
        </button>

      </div>

    </div>
  );
}